#!/bin/bash
#
# Get the latest API spec information from botocore
#
set -e

mkdir -p lib/vendor
cd lib/vendor
git init
git config core.sparsecheckout true
echo "botocore/data" > .git/info/sparse-checkout
git remote add -f origin git@github.com:boto/botocore.git || true
git pull origin develop
rm -rf .git
