#!/bin/bash
set -e

DIR=$PWD

# Do the needful with terraform
$DIR/scripts/terraform

# generate tf grammar wasm
# must have DOCKER for this to work
npx tree-sitter generate --no-bindings
cp $DIR/node_modules/tree-sitter-hcl/src/scanner.cc src/scanner.cc
echo "building hcl wasm tree-sitter parser"
npx tree-sitter build-wasm

# Copy tree-sitter.wasm to root of the project for playground
cp node_modules/web-tree-sitter/tree-sitter.wasm .


