#!/bin/bash
#
# Get the latest terraform names_data for converting resource types to service::product values
# Use this script to generate new mappings for hcl resources
#
set -e

echo "cloning terraform repo. we need some of this data..."
./scripts/git terraform hashicorp/terraform-provider-aws \
  d62c51bb2f043eee5ab85dffae0de9d8bbdc67e2 \
  names/names_data.csv

echo "generating hcl grammar for tf services automatically from terraform repo"
node --no-lazy \
  -r ts-node/register/transpile-only \
  --preserve-symlinks \
  --preserve-symlinks-main \
  $PWD/scripts/terraform.ts
