#!/bin/bash
#
# Get the latest terraform names_data for converting resource types to service::product values
# Use this script to generate new mappings for hcl resources
#
set -e

echo "cloning terraform repo. we need some of this data..."
./scripts/git terraform hashicorp/terraform-provider-aws \
  4e5e50476505a740604f7bdd070d3cd45ec2fe37 \
  names/names_data.csv \
  internal/service

echo "generating hcl grammar for tf services automatically from terraform repo"
node --no-lazy \
  -r ts-node/register/transpile-only \
  --preserve-symlinks \
  --preserve-symlinks-main \
  $PWD/scripts/tf/grammar.ts
