name: main
on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
